import Head from "next/head";
import CollectionDetails from "../../src/Components/collectionDetails/CollectionDetails";
import Footer from "../../src/Components/footer/Footer";
import Header from "../../src/Components/header/Header";

export default function collectionName() {
  return (
    <div>
      <Head>
        <title>colection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <header>
        <Header backColor={"headerColor"} />
      </header>
      <main><CollectionDetails/></main>
      <footer>
        <Footer />
      </footer>
    </div>
  );
}
