import Head from "next/head";
import Productpage from "../../src/Components/productPage/Productpage";
import Footer from "../../src/Components/footer/Footer";
import Header from "../../src/Components/header/Header";
import callApi from "../../src/api/callApi";
import { useEffect } from "react";
import { BASE_URL, GET_PRODUCT, GET_WITHLABLE } from "../../src/api/urls";
export default function productname({ product, similar }) {
  console.log(similar)
  return (
    <div>
      <Head>
        <title>product</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <header>
        <Header backColor={"headerColor"} />
      </header>
      <main>
        <Productpage product={product.data} similar={similar} />
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  );
}

export async function getServerSideProps(context) {
  const { params } = context;
  const { productname } = params;
  const data = await callApi(
    `${BASE_URL + GET_PRODUCT}?id=${productname}`,
    "GET",
    "{}"
  );
  const similar = await callApi(
    `${BASE_URL + GET_WITHLABLE}?Type=${data.data.type}`,
    "GET",
    "{}"
  );

  return {
    props: { product: data, similar: similar } // will be passed to the page component as props
  };
}
