import Head from "next/head";
import Productpage from "../../src/Components/productPage/Productpage";
import Footer from "../../src/Components/footer/Footer";
import Header from "../../src/Components/header/Header";

export default function productname() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Header backColor={"headerColor"} />
      </header>
      <main>
        <Productpage />
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  );
}
