import Head from "next/head";
import callApi from "../../src/api/callApi";
import { BASE_URL, GET_WITHLABLE } from "../../src/api/urls";
import Category from "../../src/Components/category/Category";
import Footer from "../../src/Components/footer/Footer";
import Header from "../../src/Components/header/Header";
export default function categoryname({ category }) {
  return (
    <div>
      <Head>
        <title>Tiola category</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <header>
        <Header backColor={"headerColor"} />
      </header>

      <main>
        <Category data={category.data} />
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  );
}

export async function getServerSideProps(context) {
  const { params } = context;
  const { categoryname } = params;
  var myHeaders = new Headers();
  myHeaders.append("Content-Type", "application/json");
  const data = await callApi(
    `${BASE_URL + GET_WITHLABLE}?Type=${categoryname}`,
    "{}",
    myHeaders,
    "GET"
  );

  return {
    props: { category: data } // will be passed to the page component as props
  };
}
