import Head from "next/head";
import callApi from "../../src/api/callApi";
import { BASE_URL, GET_WITHLABLE } from "../../src/api/urls";
import Category from "../../src/Components/category/Category";
import Footer from "../../src/Components/footer/Footer";
import Header from "../../src/Components/header/Header";
import { useRouter } from "next/router";
import { useTranslation } from "react-i18next";
export default function Categoryname({ category }) {
  const router = useRouter();
  const { t } = useTranslation();
  if (router.query.categoryname === "shawl") {
    var name = t("shawl");
  } else if (router.query.categoryname === "scarf") {
    name = t("scarf");
  } else if (router.query.categoryname === "headgear") {
    name = t("headgear");
  } else {
    name = t("tiolaCategoyTitle");
  }

  return category === 404 ? (
    router.push({ pathname: "/errorpage" })
  ) : (
    <div>
      <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <header>
        <Header backColor={"headerColor"} />
      </header>

      <main>
        <Category data={category[0].data} />
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  );
}

export async function getServerSideProps(context) {
  const { params } = context;
  const { categoryname } = params;
  var myHeaders = {"Content-Type": "application/json"};
  
  const data = await callApi(
    `${BASE_URL + GET_WITHLABLE}?Type=${categoryname}`,
    "{}",
    myHeaders,
    "GET"
  );

    return {
      props: { category: data } // will be passed to the page component as props
    };

}
