import Head from "next/head";
import { useTranslation } from "react-i18next";
import AboutUsTiola from "../src/Components/aboutus/AboutUsTiola";
import Footer from "../src/Components/footer/Footer";
import Header from "../src/Components/header/Header";
export default function AboutUs() {
  const {t}=useTranslation()
  return (
    <div>
      <Head>
        <title>{t("AboutUs")}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <header>
        <Header backColor={"headerColor"} />
      </header>

      <main>
          <AboutUsTiola/>
      </main>

   
    </div>
  );
}
