import Head from "next/head";
import Footer from "../src/Components/footer/Footer";
import Header from "../src/Components/header/Header";
import TiolaCollections from "../src/Components/pageCollentions/MyCollection/TiolaCollections";

export default function collection() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Header backColor={"headerColor"} />
      </header>
      <main>
          <TiolaCollections/>
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  );
}
