import Head from "next/head";
import callApi from "../src/api/callApi";
import { BASE_URL, ALL_COLLECTION } from "../src/api/urls";
import Footer from "../src/Components/footer/Footer";
import Header from "../src/Components/header/Header";
import TiolaCollections from "../src/Components/pageCollentions/MyCollection/TiolaCollections";

export default function collections({ allCollection }) {
  console.log(allCollection);
  return (
    <div>
      <Head>
        <title>Tiola Colections</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <header>
        <Header backColor={"headerColor"} />
      </header>
      <main>
        <TiolaCollections data={allCollection.data} />
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  );
}
export async function getServerSideProps(context) {
  const { params } = context;
  var myHeaders = new Headers();
  myHeaders.append("Content-Type", "application/json");


  const data = await callApi(BASE_URL + ALL_COLLECTION, "{}", myHeaders, "GET");

  return {
    props: { allCollection: data } // will be passed to the page component as props
  };
}
