import Head from "next/head";
import Footer from "../src/Components/footer/Footer";
import Header from "../src/Components/header/Header";
import ContactUs from "../src/Components/ContactUs/ContactUs";
export default function explore() {
  return (
    <div>
      <Head>
        <title>Tiola Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <header>
        <Header backColor={"headerColor"} />
      </header>

      <main>
        <ContactUs />
      </main>

      <footer>
        <Footer />
      </footer>
    </div>
  );
}