import Head from "next/head";
import React from "react";
import ErrorCm from "../src/tools/errorPage/ErrorCm";
import cactus from "../public/Assets/images/cactus.png";

const dfmdkfjklndkcbhcvsx = () => {
  return (
    <>
      <Head>
        <title>Error</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <main>
        <ErrorCm img={cactus} txt="You Can Not Connect to Server " />
      </main>
    </>
  );
};

export default dfmdkfjklndkcbhcvsx;
