import Head from "next/head";
import Footer from "../src/Components/footer/Footer";
import Header from "../src/Components/header/Header";
import ExploreMain from "../src/Components/Explore/ExploreMain";
import { BASE_URL, GET_ALL_PRODUCT } from "../src/api/urls";
import callApi from "../src/api/callApi";
import ScreenLoader from "../src/tools/screenLoader/ScreenLoader";
import { useTranslation } from "react-i18next";
export default function Explore({ explore }) {
  const {t}=useTranslation()
  return (
    <div>
      <Head>
        <title>{t("explore")}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <header>
        <Header backColor={"headerColor"} />
      </header>

     
        <main>
          <ExploreMain data={explore[0].data} />
        </main>
    

      <footer>
        <Footer />
      </footer>
    </div>
  );
}

export async function getServerSideProps(context) {
  var myHeaders = {"Content-Type": "application/json"}

  const data = await callApi(
    BASE_URL + GET_ALL_PRODUCT,
    "{}",
    myHeaders,
    "GET"
  );

  return {
    props: { explore: data } // will be passed to the page component as props
  };
}
