import Head from "next/head";
import { useEffect } from "react";
import { useSelector } from "react-redux";
import UserFactor from "../src/Components/factor/UserFactor";
import Footer from "../src/Components/footer/Footer";
import Header from "../src/Components/header/Header";
import Loader from "../src/tools/loader/Loader";
import ScreenLoader from "../src/tools/screenLoader/ScreenLoader";
export default function SigninUser() {
  if (typeof window !== "undefined") {
    var root = document.documentElement;
    var ls = localStorage.getItem("userToken");
  }
  const state = useSelector((state) => state.stateRegister);

  return (
    <div>
      <Head>
        <title>Tiola factor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <header>
        <Header backColor={"headerColor"} />
      </header>
      {state.userDataLoader ? (
        <ScreenLoader />
      ) : (
        <main>
          <UserFactor />
        </main>
      )}
      <footer>
        <Footer />
      </footer>
    </div>
  );
}
