import Head from "next/head";
import Footer from "../src/Components/footer/Footer";
import Header from "../src/Components/header/Header";
import { useTranslation } from "react-i18next";
import Faq from "../src/Components/faq/Faq";

export default function FaqPage() {
  const { t } = useTranslation();
  return (
    <div>
      <Head>
        <title>{t("FAQ")}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <header>
        <Header backColor={"headerColor"} />
      </header>

      <main>
        <Faq />
      </main>

      <footer>
        <Footer />
      </footer>
    </div>
  );
}
