import Head from "next/head";
import Collection from "../src/Components/collection/Collection";
import Footer from "../src/Components/footer/Footer";
import Header from "../src/Components/header/Header";
import HeroSection from "../src/Components/heroSection/HeroSection";
import ProductSlider from "../src/Components/productSlider/ProductSlider";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Header backColor={"headerBlur"} />
      </header>
      <main>
        <HeroSection />
        <ProductSlider />
        <Collection />
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  );
}
