import React from "react";
import Head from "next/head";
import { useTranslation } from "react-i18next";

const Ourteam = () => {
  const { t } = useTranslation();
  return (
    <Head>
      <title>{t("ourteam")}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/logo.ico" />
    </Head>
  );
};

export default ourteam;
