import Head from "next/head";
import Footer from "../src/Components/footer/Footer";
import Header from "../src/Components/header/Header";
import { useTranslation } from "react-i18next";
import OurTeam from "../src/Components/ourTeam/OurTeam";


export default function ourteam() {

  const { t } = useTranslation();

  return (
    <div>
      <Head>
        <title>{t("ourTeam")}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <header>
        <Header backColor={"headerColor"} />
      </header>

      <main>
        <OurTeam />
      </main>

      <footer>
        <Footer />
      </footer>
    </div>
  );
}
