import React from "react";
import Head from "next/head";
import { useTranslation } from "react-i18next";
import Footer from "../src/Components/footer/Footer";
import Header from "../src/Components/header/Header";
import OurTeam from "../src/Components/ourteamPage/OurTeam";

const Ourteams = () => {
  const { t } = useTranslation();
  return (
    <>
      <Head>
        <title>{t("ourteam")}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <header>
        <Header backColor={"headerColor"} />
      </header>
      <main>
        <OurTeam />
      </main>
      <footer className="noneM">
        <Footer/>
      </footer>
    </>
  );
};

export default Ourteams;
