import { useEffect, useState } from "react";
import Head from "next/head";
import { useTranslation } from "react-i18next";
import { useSelector } from "react-redux";
import Footer from "../src/Components/footer/Footer";
import Header from "../src/Components/header/Header";
import UserProfile from "../src/Components/profile/UserProfile";
import ScreenLoader from "../src/tools/screenLoader/ScreenLoader";
import { notify } from "../src/tools/toast/toast";
import { useRouter } from "next/dist/client/router";

export default function Profile() {
  const state = useSelector((state) => state.stateRegister);
  const lang = useSelector(state =>state.stateLang.lng);
 const {t}=useTranslation()
  const router = useRouter()
 useEffect(()=> {
  const tokenLocal = JSON.parse(window.localStorage.getItem("userToken"));
  console.log("hello", tokenLocal)
  if(tokenLocal === null){
    console.log(router, "hihi")
    router.push({pathname: "/"})
  }
 }, [])

  return (
    <div>
      <Head>
        <title>{t("profile")}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <header>
        <Header backColor={"headerColor"} />
      </header>
      {state.userDataLoader ? (
        <ScreenLoader />
      ) : (
        <main>
          <UserProfile />
        </main>
      )}
      <footer>
        <Footer />
      </footer>
    </div>
  );
}
