import Head from "next/head";
import { useLayoutEffect, useState } from "react";
import Footer from "../src/Components/footer/Footer";
import Header from "../src/Components/header/Header";
import MBproductCategory from "../src/Components/shopPage/MBproductCategory/MBproductCategory";
import ProductsCategory from "../src/Components/shopPage/productsCategorization/ProductsCategory";

export default function Shop() {
  const [size, setSize] = useState([0]);
  useLayoutEffect(() => {
    function updateSize() {
      setSize([window.innerWidth]);
    }
    window.addEventListener("resize", updateSize);
    updateSize();
    return () => window.removeEventListener("resize", updateSize);
  }, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Header backColor={"headerColor"} />
      </header>
      {size > 769 ? (
        <main>
          <ProductsCategory />
          <ProductsCategory reverse={true} />
          <ProductsCategory />
        </main>
      ) : (
        <main>
          <MBproductCategory />
          <MBproductCategory reverse={true} />
          <MBproductCategory />
        </main>
      )}
      <footer>
        <Footer />
      </footer>
    </div>
  );
}
