import Head from "next/head";
import { useEffect } from "react";
import { useTranslation } from "react-i18next";
import { useDispatch, useSelector } from "react-redux";
import callApi from "../src/api/callApi";
import { BASE_URL, TYPE_PAGE_API } from "../src/api/urls";
import Footer from "../src/Components/footer/Footer";
import Header from "../src/Components/header/Header";
import ShopPage from "../src/Components/shopPage/ShopPage";
import { getshopCategory } from "../src/redux/shop/shopActions";
import Loader from "../src/tools/loader/Loader";
import { notify } from "../src/tools/toast/toast";
export default function Shop({ shop }) {
  const { t } = useTranslation();
  const state = useSelector((state) => state.stateShop);
  const user = useSelector(state => state.stateRegister);
  const lang = useSelector(state =>  state.stateLang.lng);
  const dispatch = useDispatch();
  
  useEffect(() => {
    dispatch(getshopCategory(shop[0]));
  }, [shop[0]]);
  
  return (
    <div>
      <Head>
        <title>{t("tiolaShop")}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <header>
        <Header backColor={"headerColor"} />
      </header>
      {state.loading ? (
        <Loader />
      ) : (
        <main>
          <ShopPage />
        </main>
      )}
      <footer>
        <Footer />
      </footer>
    </div>
  );
}
export async function getServerSideProps(context) {
  var myHeaders = {"Content-Type": "application/json"};

  const data = await callApi(BASE_URL + TYPE_PAGE_API, "{}", myHeaders, "GET");
  return {
    props: { shop: data } // will be passed to the page component as props
  };
}
