import Head from "next/head";
import { useTranslation } from "react-i18next";

import Header from "../src/Components/header/Header";
import Register from "../src/Components/register/Register";
export default function SignUpUser() {
const {t}=useTranslation()
  return (
    <div>
      <Head>
        <title>signUp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <header>
        <Header backColor={"headerColor"} />
      </header>

      <main>
        <Register title={t("signup")} />
      </main>

    </div>
  );
}
