import React from "react";
import ErrorCm from "../src/tools/errorPage/ErrorCm";
import Head from "next/head";
import updatingImg from "../public/Assets/images/updating.png";
const updating = () => {
  return (
    <>
      <Head>
        <title>updating</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <main>
        <ErrorCm img={updatingImg} txt="Updating Now Be Patient" />
      </main>
    </>
  );
};

export default updating;
