import Head from "next/head";
import Footer from "../../src/Components/footer/Footer";
import Header from "../../src/Components/header/Header";
import BlogDetail from "../../src/Components/blogs/blogsDetail/BlogDetail";
import { useTranslation } from "react-i18next";
export default function Blogs() {
  const { t } = useTranslation();
  return (
    <div>
      <Head>
        <title>{t("tiolaBlogsTitle")}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <header>
        <Header backColor={"headerColor"} />
      </header>

      <main>
        <BlogDetail />
      </main>

      <footer>
        <Footer />
      </footer>
    </div>
  );
}
